version:  '2'
services:
  mongodb:
   image: mongo
   ports:
     - "27017:27017"

  mongo-seed:
   build: ./mongo-seed
   links:
     - mongodb

  node-red:
    image: jamesbrink/node-red:0.16.2
    ports:
      - "1880:1880"
    volumes:
      - /Node-Red:/data
